### ISSUE TITLE
JupyterLite replite demo on ReadTheDocs main page fails to execute command

### ISSUE THREAD

**Issue by tylere** [jupyterlite/jupyterlite-sphinx#90]
## Description

The JupyterLite replite directive demo on the main ReadTheDocs page fails to execute commands.

Using Chrome:
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/92862/224554699-3b37aa86-6ccf-4cb8-a069-d1de4c1ed513.png">

Using Safari:
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/92862/224555338-629cba80-548f-4ede-b3af-23b3c00e94f8.png">

## Reproduce

1. Go to https://jupyterlite-sphinx.readthedocs.io/en/latest/
2. Note that the kernel command does not finish executing.
3. Open the Chrome developer tools.

## Expected behavior

The command in the JupyterLite embed should return output.

## Context

- JupyterLite version: unknown
- Operating System and version: Apple M1 Max, MacOS 13.2 (22D49)
- Browser and version: 
  - Chrome Version 110.0.5481.177 (Official Build) (arm64)
  - Safari Version 16.3 (18614.4.6.1.5)

<details><summary>Browser Output</summary>
<pre>
pydata-sphinx-theme.js?digest=12da95d707ffb74b382d:1 [PST]: Changed to auto mode using the light theme.
243.d9d134ad2ffdfb9205b3.js:2 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at https://jupyterlite-sphinx.readthedocs.io/en/latest/lite/extensions/jupyter-leaflet/static/243.d9d134ad2ffdfb9205b3.js:2:3143
    at C.extend (https://jupyterlite-sphinx.readthedocs.io/en/latest/lite/extensions/jupyter-leaflet/static/243.d9d134ad2ffdfb9205b3.js:2:3162)
    at 665 (https://jupyterlite-sphinx.readthedocs.io/en/latest/lite/extensions/jupyter-leaflet/static/665.3328989849f89dbc115a.js:1:4763)
    at j (https://jupyterlite-sphinx.readthedocs.io/en/latest/lite/extensions/jupyter-leaflet/static/remoteEntry.8f5cefaa26fbae099326.js:1:795)
    at https://jupyterlite-sphinx.readthedocs.io/en/latest/lite/extensions/jupyter-leaflet/static/remoteEntry.8f5cefaa26fbae099326.js:1:3895
    at w.<computed> (https://jupyterlite-sphinx.readthedocs.io/en/latest/lite/extensions/jupyter-leaflet/static/remoteEntry.8f5cefaa26fbae099326.js:1:9878)
    at j (https://jupyterlite-sphinx.readthedocs.io/en/latest/lite/extensions/jupyter-leaflet/static/remoteEntry.8f5cefaa26fbae099326.js:1:795)
    at 8197 (https://jupyterlite-sphinx.readthedocs.io/en/latest/lite/extensions/jupyter-leaflet/static/138.002dd8f96b6a3a975f92.js:1:60128)
    at j (https://jupyterlite-sphinx.readthedocs.io/en/latest/lite/extensions/jupyter-leaflet/static/remoteEntry.8f5cefaa26fbae099326.js:1:795)
    at 4795 (https://jupyterlite-sphinx.readthedocs.io/en/latest/lite/extensions/jupyter-leaflet/static/138.002dd8f96b6a3a975f92.js:1:43984)
(anonymous) @ 243.d9d134ad2ffdfb9205b3.js:2
C.extend @ 243.d9d134ad2ffdfb9205b3.js:2
665 @ 665.3328989849f89dbc115a.js:1
j @ remoteEntry.8f5cefaa26fbae099326.js:1
(anonymous) @ remoteEntry.8f5cefaa26fbae099326.js:1
w.<computed> @ remoteEntry.8f5cefaa26fbae099326.js:1
j @ remoteEntry.8f5cefaa26fbae099326.js:1
8197 @ 138.002dd8f96b6a3a975f92.js:1
j @ remoteEntry.8f5cefaa26fbae099326.js:1
4795 @ 138.002dd8f96b6a3a975f92.js:1
j @ remoteEntry.8f5cefaa26fbae099326.js:1
560 @ 138.002dd8f96b6a3a975f92.js:1
j @ remoteEntry.8f5cefaa26fbae099326.js:1
8138 @ 138.002dd8f96b6a3a975f92.js:1
j @ remoteEntry.8f5cefaa26fbae099326.js:1
3738 @ 738.12432ed2776b6b36ef53.js:1
j @ remoteEntry.8f5cefaa26fbae099326.js:1
(anonymous) @ remoteEntry.8f5cefaa26fbae099326.js:1
r @ index.js:26
await in r (async)
(anonymous) @ index.js:128
a @ index.js:121
await in a (async)
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
68653 @ bootstrap.js:65
v @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ bundle.js?_=cd5a1e6:1
index.ts:518 Plugin '@jupyterlab/drawio-extension:plugin' failed to activate.
(anonymous) @ index.ts:518
Promise.catch (async)
(anonymous) @ index.ts:517
t.start @ index.ts:516
a @ index.js:238
await in a (async)
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
68653 @ bootstrap.js:65
v @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ bundle.js?_=cd5a1e6:1
index.ts:519 Error: No provider for: @jupyterlab/application:ILayoutRestorer.
    at u.<anonymous> (index.ts:427:29)
    at tslib.es6.js:102:23
    at Object.next (tslib.es6.js:83:53)
    at tslib.es6.js:76:71
    at new Promise (<anonymous>)
    at u (tslib.es6.js:72:12)
    at t.resolveRequiredService (index.ts:423:35)
    at index.ts:322:52
    at Array.map (<anonymous>)
    at u.<anonymous> (index.ts:322:38)
(anonymous) @ index.ts:519
Promise.catch (async)
(anonymous) @ index.ts:517
t.start @ index.ts:516
a @ index.js:238
await in a (async)
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
68653 @ bootstrap.js:65
v @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ bundle.js?_=cd5a1e6:1
index.ts:518 Plugin 'jupyterlab-kernelspy' failed to activate.
(anonymous) @ index.ts:518
Promise.catch (async)
(anonymous) @ index.ts:517
t.start @ index.ts:516
a @ index.js:238
await in a (async)
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
68653 @ bootstrap.js:65
v @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ bundle.js?_=cd5a1e6:1
index.ts:519 Error: No provider for: @jupyterlab/notebook:INotebookTracker.
    at u.<anonymous> (index.ts:427:29)
    at tslib.es6.js:102:23
    at Object.next (tslib.es6.js:83:53)
    at tslib.es6.js:76:71
    at new Promise (<anonymous>)
    at u (tslib.es6.js:72:12)
    at t.resolveRequiredService (index.ts:423:35)
    at index.ts:322:52
    at Array.map (<anonymous>)
    at u.<anonymous> (index.ts:322:38)
(anonymous) @ index.ts:519
Promise.catch (async)
(anonymous) @ index.ts:517
t.start @ index.ts:516
a @ index.js:238
await in a (async)
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
68653 @ bootstrap.js:65
v @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ bundle.js?_=cd5a1e6:1
service-manager.ts:45 JupyterLite ServiceWorker was already registered
index.ts:235 Kernel filesystem and JupyterLite contents will be synced
index.ts:65 Pyolite contents will be synced with Jupyter Contents
pyodide.asm.js:10 Loading micropip, pyparsing, packaging
pyodide.asm.js:10 Loaded pyparsing, packaging, micropip
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/cell-toolbar-extension:plugin) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/cell-toolbar-extension:plugin) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/csvviewer-extension:csv) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/csvviewer-extension:csv) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/csvviewer-extension:tsv) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/csvviewer-extension:tsv) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/filebrowser-extension:widget) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/filebrowser-extension:widget) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/fileeditor-extension:plugin) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/fileeditor-extension:plugin) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/htmlviewer-extension:plugin) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/htmlviewer-extension:plugin) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:42 Settings failed to load for (@jupyterlab/notebook-extension:panel) [{…}]
(anonymous) @ settingsplugin.ts:42
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
settingsplugin.ts:44 This may happen if {autoStart: false} in (@jupyterlab/notebook-extension:panel) or if it is one of the deferredExtensions in page config.
(anonymous) @ settingsplugin.ts:44
await in (anonymous) (async)
(anonymous) @ settingsplugin.ts:34
pyodide.asm.js:10 Loading sqlite3
pyodide.asm.js:10 Loaded sqlite3
kernel.ts:49 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/_pyodide/_base.py", line 531, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 359, in run_async
    await coroutine
  File "<exec>", line 5, in <module>
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/piplite/piplite.py", line 102, in _install
    return await _micropip.install(
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 573, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 340, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 448, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 463, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 337, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 448, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 463, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 337, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 418, in add_requirement_inner
    if self.check_version_satisfied(req):
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 364, in check_version_satisfied
    raise ValueError(
ValueError: Requested 'packaging>=22.0', but packaging==21.3 is already installed

    at new_error (pyodide.asm.js:10:179954)
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at method_call_trampoline (pyodide.asm.js:10:229349)
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at pyodide.asm.wasm
    at Module.callPyObjectKwargs (pyodide.asm.js:10:123403)
    at Module.callPyObject (pyodide.asm.js:10:123781)
    at wrapper (pyodide.asm.js:10:219389)
deserialize @ comlink.mjs:57
b @ comlink.mjs:272
await in b (async)
g @ kernel.ts:28
create @ index.ts:70
await in create (async)
startNew @ kernels.ts:141
startNew @ sessions.ts:108
(anonymous) @ index.ts:442
route @ router.ts:89
await in route (async)
fetch @ app.ts:77
e.handleRequest @ serverconnection.ts:313
e.makeRequest @ serverconnection.ts:145
t.startSession @ restapi.ts:107
startNew @ manager.ts:161
_changeKernel @ sessioncontext.tsx:895
_startIfNecessary @ sessioncontext.tsx:836
_initialize @ sessioncontext.tsx:758
await in _initialize (async)
initialize @ sessioncontext.tsx:725
D @ panel.ts:88
B @ index.ts:251
await in B (async)
execute @ index.ts:492
e.execute @ index.ts:437
(anonymous) @ index.ts:149
Promise.then (async)
activate @ index.ts:148
(anonymous) @ index.ts:329
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @tylere for the report.

For the first issue it looks like some dependencies might have drifted over time. Although they seem to be specified here: https://github.com/jupyterlite/jupyterlite-sphinx/blob/11f65ac54fd20938a3bbcb9780741504b8dcfcbb/docs/jupyter_lite_config.json#L24

Maybe it would be simpler to use `jupyterlite-xeus-python` for the demo on ReadTheDocs to avoid such issues.

The second one is tracked https://github.com/jupyterlite/jupyterlite/issues/944.

**Comment by jtpio** [comment]
@tylere is the first issue still happening for you with the latest state of the docs?

This is looking fine for me on both Firefox and Chromium:

![image](https://user-images.githubusercontent.com/591645/225555685-c284e1d0-3ade-47e6-b1bb-52d4835d5ee5.png)

**Comment by jtpio** [comment]
There was an update in https://github.com/jupyterlite/jupyterlite-sphinx/pull/89 which update Pyodide, and triggered a new doc build.

**Comment by tylere** [comment]
Confirming that it now works for me in Chrome:
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/92862/225749760-73038da6-54ca-4b09-9e47-9a79108e93fc.png">
